# 데이터 업로드

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('./data/2020가계부채/가계부채_2020_rev.csv', engine='python', encoding='cp949')
data

,Unnamed: 0,조사연도,가구고유번호(MD제공용),가중치,수도권여부,가구주 성별,가구원수,노인가구,조손가구,한부모가구,...,원리금 상환으로 인한 가계지출 감소 항목,부채 상환 가능 시기,가구주 은퇴여부,가구주 미은퇴시_은퇴연령,가구주 미은퇴시_최소생활비,가구주 미은퇴시_적정생활비,가구주 미은퇴시_노후준비상황,가구주 은퇴시_가구주 은퇴실제 연령,가구주 은퇴시_적정생활비 충당여부,가구주 은퇴시_생활비 재원마련(2014년~)
0,1,2020,10000112,1531.602344,수도권,남자,3,그 외 가구,그 외 가구,그 외 가구,...,NaN,대출기한 내에 갚을 수 있다,은퇴하지 않았다,70.0,400,500,보통이다,NaN,NaN,NaN
1,2,2020,10000132,1314.119926,수도권,여자,2,그 외 가구,그 외 가구,그 외 가구,...,의류구입비,대출기한 내에 갚을 수 있다,은퇴하지 않았다,70.0,500,700,보통이다,NaN,NaN,NaN
2,3,2020,10000162,1098.806050,수도권,여자,1,노인가구,그 외 가구,그 외 가구,...,NaN,NaN,은퇴하지 않았다,75.0,100,150,보통이다,NaN,NaN,NaN
3,4,2020,10000182,1124.027871,수도권,남자,2,그 외 가구,그 외 가구,그 외 가구,...,NaN,NaN,은퇴하지 않았다,70.0,200,250,잘 되어 있지 않다,NaN,NaN,NaN
4,5,2020,10000192,1098.806050,수도권,여자,1,그 외 가구,그 외 가구,그 외 가구,...,NaN,NaN,은퇴하지 않았다,65.0,250,300,보통이다,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18059,18060,2020,993800291,601.643255,비수도권,남자,3,그 외 가구,그 외 가구,그 외 가구,...,저축 및 금융자산 투자,대출기한 내에 갚을 수 있다,은퇴하지 않았다,55.0,400,500,보통이다,NaN,NaN,NaN
18060,18061,2020,994800251,384.069810,비수도권,남자,5,그 외 가구,그 외 가구,그 외 가구,...,저축 및 금융자산 투자,대출기한 내에 갚을 수 있다,은퇴하지 않았다,60.0,300,600,잘 되어 있다,NaN,NaN,NaN
18061,18062,2020,994800261,359.114694,비수도권,남자,5,그 외 가구,그 외 가구,그 외 가구,...,NaN,대출기한 내에 갚을 수 있다,은퇴하였다,NaN,0,0,NaN,56.0,보통이다,"국민연금, 공무원연금 등 공적 연금"
18062,18063,2020,994800291,416.635211,비수도권,여자,2,그 외 가구,그 외 가구,그 외 가구,...,NaN,NaN,은퇴하지 않았다,60.0,200,300,보통이다,NaN,NaN,NaN
18063,18064,2020,995800261,769.826228,비수도권,남자,5,그 외 가구,그 외 가구,그 외 가구,...,NaN,대출기한 내에 갚을 수 있다,은퇴하지 않았다,60.0,150,300,아주 잘 되어 있다,NaN,NaN,NaN

In [3]:
data['조사연도']

0        2020
1        2020
2        2020
3        2020
4        2020
         ...
18059    2020
18060    2020
18061    2020
18062    2020
18063    2020
Name: 조사연도, Length: 18064, dtype: int64

In [4]:
data.describe()

,Unnamed: 0,조사연도,가구고유번호(MD제공용),가중치,가구원수,가구주 만나이,자산,금융자산,저축액,적립 및 예치식 저축,...,세금(보완),공적연금·사회보험료(보완),가구간 이전지출(조사),비영리단체 이전지출(조사),연간지급이자(조사),생계에 부담이 될것으로 생각되는 소득대비 원리금상환액 비중,가구주 미은퇴시_은퇴연령,가구주 미은퇴시_최소생활비,가구주 미은퇴시_적정생활비,가구주 은퇴시_가구주 은퇴실제 연령
count,18064.000000,18064.0,1.806400e+04,18064.000000,18064.000000,18064.000000,1.806400e+04,18064.000000,18064.000000,18064.000000,...,18064.000000,18064.000000,18064.000000,18064.000000,18064.000000,3212.000000,14274.000000,18064.000000,18064.000000,3790.00000
mean,9032.500000,2020.0,4.874675e+08,1123.272088,2.496402,57.595937,4.124337e+04,9534.619298,7284.317759,6899.865368,...,321.767992,318.079384,142.861271,57.013231,172.466729,21.424658,68.746182,158.560009,227.115977,63.42190
std,5214.771967,0.0,2.871545e+08,569.662922,1.231130,14.837408,6.663669e+04,20982.055400,19088.965817,18633.983183,...,1248.688890,383.556636,320.445918,173.464640,483.027662,10.496648,7.349410,107.102618,152.358403,9.94318
min,1.000000,2020.0,1.000011e+07,73.589147,1.000000,20.000000,1.000000e+00,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,50.000000,0.000000,0.000000,15.00000
25%,4516.750000,2020.0,2.319004e+08,708.198826,2.000000,46.000000,7.628750e+03,1208.000000,680.750000,626.000000,...,18.000000,25.000000,0.000000,0.000000,0.000000,10.000000,65.000000,100.000000,150.000000,60.00000
50%,9032.500000,2020.0,4.917003e+08,986.560538,2.000000,58.000000,2.280700e+04,4430.000000,3090.000000,2923.000000,...,69.000000,200.000000,40.000000,0.000000,0.000000,20.000000,70.000000,180.000000,250.000000,63.00000
75%,13548.250000,2020.0,7.306002e+08,1418.695427,3.000000,68.000000,4.864850e+04,10884.250000,8050.000000,7578.500000,...,231.250000,470.000000,150.000000,42.000000,180.000000,30.000000,70.000000,200.000000,300.000000,70.00000
max,18064.000000,2020.0,9.958003e+08,4022.776532,8.000000,102.000000,1.518417e+06,937840.000000,937840.000000,937840.000000,...,58970.000000,7377.000000,9010.000000,10000.000000,21570.000000,70.000000,100.000000,1000.000000,1500.000000,91.00000

In [13]:
data.isnull().sum()

조사연도                            0
가구고유번호(MD제공용)                   0
가중치                             0
수도권여부                           0
가구주 성별                          0
                            ...
가구주 미은퇴시_적정생활비                  0
가구주 미은퇴시_노후준비상황              3790
가구주 은퇴시_가구주 은퇴실제 연령         14274
가구주 은퇴시_적정생활비 충당여부          14274
가구주 은퇴시_생활비 재원마련(2014년~)    14274
Length: 153, dtype: int64

In [35]:
df1=pd.DataFrame(data,columns=['부채상환 방법','원리금 연체 여부', '원리금 연체 사유', '30일 이상 원리금 연체 여부', '원리금 상환이 생계에 부담되는 정도'])
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18064 entries, 0 to 18063
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   부채상환 방법              4305 non-null   object
 1   원리금 연체 여부            9733 non-null   object
 2   원리금 연체 사유            1027 non-null   object
 3   30일 이상 원리금 연체 여부     1027 non-null   object
 4   원리금 상환이 생계에 부담되는 정도  9733 non-null   object
dtypes: object(5)
memory usage: 705.8+ KB

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18064 entries, 0 to 18063
Columns: 154 entries, Unnamed: 0 to 가구주 은퇴시_생활비 재원마련(2014년~)
dtypes: float64(36), int64(69), object(49)
memory usage: 21.2+ MB

In [69]:
data['부동산 투자를 하지 않는 이유']

0                    NaN
1                    NaN
2          부동산에 대한 정보 부족
3                    NaN
4          부동산에 대한 정보 부족
              ...
18059         금융자산 등에 투자
18060    세금(종합부동산세 등) 부담
18061                NaN
18062         금융자산 등에 투자
18063       부동산 가격의 불확실성
Name: 부동산 투자를 하지 않는 이유, Length: 18064, dtype: object

In [114]:
df2=pd.DataFrame(data,columns=['부동산 투자를 하지 않는 이유'])
df2

      부동산 투자를 하지 않는 이유
0                  NaN
1                  NaN
2        부동산에 대한 정보 부족
3                  NaN
4        부동산에 대한 정보 부족
...                ...
18059       금융자산 등에 투자
18060  세금(종합부동산세 등) 부담
18061              NaN
18062       금융자산 등에 투자
18063     부동산 가격의 불확실성

[18064 rows x 1 columns]

In [115]:
df2.fillna('자료없음', inplace=True)
df2

      부동산 투자를 하지 않는 이유
0                 자료없음
1                 자료없음
2        부동산에 대한 정보 부족
3                 자료없음
4        부동산에 대한 정보 부족
...                ...
18059       금융자산 등에 투자
18060  세금(종합부동산세 등) 부담
18061             자료없음
18062       금융자산 등에 투자
18063     부동산 가격의 불확실성

[18064 rows x 1 columns]

In [78]:
# 시각화로 이상치를 확인하여 봅니다.
from matplotlib import font_manager, rc
import platform
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

font_name = font_manager.FontProperties(fname="c:/Windows/Fonts/malgun.ttf").get_name()
rc('font', family=font_name)

#그래프에서 마이너스 기호가 표시되게 하는 설정입니다.
matplotlib.rcParams['axes.unicode_minus'] = False
plt.rcParams["figure.figsize"] = (14,4)

In [92]:
df2_unique = df2['부동산 투자를 하지 않는 이유'].unique()
df2_unique

array(['자료없음', '부동산에 대한 정보 부족', '세금(종합부동산세 등) 부담', '금융자산 등에 투자', '기타',
       '부동산 가격의 불확실성'], dtype=object)

In [123]:
df2_counts = df2.value_counts()
df2_counts

부동산 투자를 하지 않는 이유
자료없음                8968
금융자산 등에 투자          2760
부동산에 대한 정보 부족       2376
부동산 가격의 불확실성        2257
세금(종합부동산세 등) 부담     1035
기타                   668
dtype: int64

In [129]:
df2_unique

array(['자료없음', '부동산에 대한 정보 부족', '세금(종합부동산세 등) 부담', '금융자산 등에 투자', '기타',
       '부동산 가격의 불확실성'], dtype=object)

In [125]:
pd.DataFrame(x=[df2_uniqu]e,y=df2_counts)

TypeError: __init__() got an unexpected keyword argument 'xx'

In [109]:
df2.isnull().sum()

부동산 투자를 하지 않는 이유    0
count               0
dtype: int64

In [95]:
df2_unique[0]

'자료없음'

# DSR, DTI 파생변수 추가
- DSR = 원리금상환액/가처분소득
- DTA = 금융부채/금융자산

- HDRI = [(1+(DSR-0.4))+(1+(DTA-1))]*100

In [242]:
data = pd.read_csv('./data/2020가계부채/가계부채_2020_rev.csv', engine='python', encoding='cp949')
data

,Unnamed: 0,조사연도,가구고유번호(MD제공용),가중치,수도권여부,가구주 성별,가구원수,노인가구,조손가구,한부모가구,...,원리금 상환으로 인한 가계지출 감소 항목,부채 상환 가능 시기,가구주 은퇴여부,가구주 미은퇴시_은퇴연령,가구주 미은퇴시_최소생활비,가구주 미은퇴시_적정생활비,가구주 미은퇴시_노후준비상황,가구주 은퇴시_가구주 은퇴실제 연령,가구주 은퇴시_적정생활비 충당여부,가구주 은퇴시_생활비 재원마련(2014년~)
0,1,2020,10000112,1531.602344,수도권,남자,3,그 외 가구,그 외 가구,그 외 가구,...,NaN,대출기한 내에 갚을 수 있다,은퇴하지 않았다,70.0,400,500,보통이다,NaN,NaN,NaN
1,2,2020,10000132,1314.119926,수도권,여자,2,그 외 가구,그 외 가구,그 외 가구,...,의류구입비,대출기한 내에 갚을 수 있다,은퇴하지 않았다,70.0,500,700,보통이다,NaN,NaN,NaN
2,3,2020,10000162,1098.806050,수도권,여자,1,노인가구,그 외 가구,그 외 가구,...,NaN,NaN,은퇴하지 않았다,75.0,100,150,보통이다,NaN,NaN,NaN
3,4,2020,10000182,1124.027871,수도권,남자,2,그 외 가구,그 외 가구,그 외 가구,...,NaN,NaN,은퇴하지 않았다,70.0,200,250,잘 되어 있지 않다,NaN,NaN,NaN
4,5,2020,10000192,1098.806050,수도권,여자,1,그 외 가구,그 외 가구,그 외 가구,...,NaN,NaN,은퇴하지 않았다,65.0,250,300,보통이다,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18059,18060,2020,993800291,601.643255,비수도권,남자,3,그 외 가구,그 외 가구,그 외 가구,...,저축 및 금융자산 투자,대출기한 내에 갚을 수 있다,은퇴하지 않았다,55.0,400,500,보통이다,NaN,NaN,NaN
18060,18061,2020,994800251,384.069810,비수도권,남자,5,그 외 가구,그 외 가구,그 외 가구,...,저축 및 금융자산 투자,대출기한 내에 갚을 수 있다,은퇴하지 않았다,60.0,300,600,잘 되어 있다,NaN,NaN,NaN
18061,18062,2020,994800261,359.114694,비수도권,남자,5,그 외 가구,그 외 가구,그 외 가구,...,NaN,대출기한 내에 갚을 수 있다,은퇴하였다,NaN,0,0,NaN,56.0,보통이다,"국민연금, 공무원연금 등 공적 연금"
18062,18063,2020,994800291,416.635211,비수도권,여자,2,그 외 가구,그 외 가구,그 외 가구,...,NaN,NaN,은퇴하지 않았다,60.0,200,300,보통이다,NaN,NaN,NaN
18063,18064,2020,995800261,769.826228,비수도권,남자,5,그 외 가구,그 외 가구,그 외 가구,...,NaN,대출기한 내에 갚을 수 있다,은퇴하지 않았다,60.0,150,300,아주 잘 되어 있다,NaN,NaN,NaN

In [243]:
data["금융자산"]

0        49000.0
1        25500.0
2         5712.0
3        14800.0
4          814.0
          ...
18059     6705.0
18060    12480.0
18061     7900.0
18062    23705.0
18063    15023.0
Name: 금융자산, Length: 18064, dtype: float64

In [244]:
data["금융부채"]

0        16000.0
1        11500.0
2            0.0
3            0.0
4            0.0
          ...
18059     2200.0
18060    22000.0
18061     8000.0
18062        0.0
18063    13000.0
Name: 금융부채, Length: 18064, dtype: float64

In [245]:
data['DTA'] = data["금융부채"]/data["금융자산"]

In [246]:
print(data['원리금상환액'], '\n')
print(data['처분가능소득(보완)[경상소득(보완)-비소비지출(보완)]'])

0          560
1         5300
2            0
3           50
4            0
         ...
18059     3020
18060     5500
18061    13600
18062        0
18063      600
Name: 원리금상환액, Length: 18064, dtype: int64

0         4599
1        15257
2          725
3         2431
4          893
         ...
18059     -390
18060    11784
18061    11560
18062     7074
18063     5404
Name: 처분가능소득(보완)[경상소득(보완)-비소비지출(보완)], Length: 18064, dtype: int64

In [247]:
data[data['처분가능소득(보완)[경상소득(보완)-비소비지출(보완)]']<0]

,Unnamed: 0,조사연도,가구고유번호(MD제공용),가중치,수도권여부,가구주 성별,가구원수,노인가구,조손가구,한부모가구,...,부채 상환 가능 시기,가구주 은퇴여부,가구주 미은퇴시_은퇴연령,가구주 미은퇴시_최소생활비,가구주 미은퇴시_적정생활비,가구주 미은퇴시_노후준비상황,가구주 은퇴시_가구주 은퇴실제 연령,가구주 은퇴시_적정생활비 충당여부,가구주 은퇴시_생활비 재원마련(2014년~),DTA
122,123,2020,11700241,965.732241,비수도권,남자,1,그 외 가구,그 외 가구,그 외 가구,...,대출기한 내에 갚을 수 있다,은퇴하지 않았다,70.0,150,200,전혀 되어 있지 않다,NaN,NaN,NaN,7.692308
197,198,2020,12700101,1367.715034,수도권,여자,1,노인가구,그 외 가구,그 외 가구,...,대출기한 내에 갚을 수 있다,은퇴하였다,NaN,0,0,NaN,70.0,여유 있다,"개인 저축액 또는 사적연금(이자, 배당금 포함)",0.334001
346,347,2020,14000342,1382.295596,수도권,여자,1,그 외 가구,그 외 가구,그 외 가구,...,상환 불가능할 것이다,은퇴하지 않았다,65.0,150,250,전혀 되어 있지 않다,NaN,NaN,NaN,2.209975
367,368,2020,14700331,1303.329861,수도권,남자,3,그 외 가구,그 외 가구,그 외 가구,...,상환 불가능할 것이다,은퇴하지 않았다,80.0,400,500,전혀 되어 있지 않다,NaN,NaN,NaN,1332.833333
438,439,2020,15900381,2509.527348,수도권,남자,3,그 외 가구,그 외 가구,그 외 가구,...,대출기한 내에 갚을 수 있다,은퇴하지 않았다,65.0,200,300,보통이다,NaN,NaN,NaN,2.907489
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17497,17498,2020,950800271,716.004552,비수도권,남자,1,노인가구,그 외 가구,그 외 가구,...,대출기한은 경과하더라도 20○○년까지는 갚을 수 있다,은퇴하지 않았다,65.0,200,250,보통이다,NaN,NaN,NaN,13.440000
17708,17709,2020,961000312,524.835526,비수도권,여자,2,그 외 가구,그 외 가구,그 외 가구,...,상환 불가능할 것이다,은퇴하였다,NaN,0,0,NaN,65.0,부족하다,"공적 수혜금(기초생활보장수급금, 기초연금 등)",2.760252
17992,17993,2020,990000342,484.166149,비수도권,남자,4,그 외 가구,그 외 가구,그 외 가구,...,대출기한 내에 갚을 수 있다,은퇴하지 않았다,85.0,50,200,보통이다,NaN,NaN,NaN,95.602294
18001,18002,2020,990600371,569.402320,비수도권,남자,1,그 외 가구,그 외 가구,그 외 가구,...,NaN,은퇴하지 않았다,70.0,200,300,보통이다,NaN,NaN,NaN,0.000000
18059,18060,2020,993800291,601.643255,비수도권,남자,3,그 외 가구,그 외 가구,그 외 가구,...,대출기한 내에 갚을 수 있다,은퇴하지 않았다,55.0,400,500,보통이다,NaN,NaN,NaN,0.328113

In [248]:
data['DSR'] = data['원리금상환액']/data['처분가능소득(보완)[경상소득(보완)-비소비지출(보완)]']

In [249]:
data['HDRI'] = ((1+data['DSR']-0.4)+(1+data['DTA']-1))*100

In [250]:
data

,Unnamed: 0,조사연도,가구고유번호(MD제공용),가중치,수도권여부,가구주 성별,가구원수,노인가구,조손가구,한부모가구,...,가구주 미은퇴시_은퇴연령,가구주 미은퇴시_최소생활비,가구주 미은퇴시_적정생활비,가구주 미은퇴시_노후준비상황,가구주 은퇴시_가구주 은퇴실제 연령,가구주 은퇴시_적정생활비 충당여부,가구주 은퇴시_생활비 재원마련(2014년~),DTA,DSR,HDRI
0,1,2020,10000112,1531.602344,수도권,남자,3,그 외 가구,그 외 가구,그 외 가구,...,70.0,400,500,보통이다,NaN,NaN,NaN,0.326531,0.121766,104.829621
1,2,2020,10000132,1314.119926,수도권,여자,2,그 외 가구,그 외 가구,그 외 가구,...,70.0,500,700,보통이다,NaN,NaN,NaN,0.450980,0.347382,139.836192
2,3,2020,10000162,1098.806050,수도권,여자,1,노인가구,그 외 가구,그 외 가구,...,75.0,100,150,보통이다,NaN,NaN,NaN,0.000000,0.000000,60.000000
3,4,2020,10000182,1124.027871,수도권,남자,2,그 외 가구,그 외 가구,그 외 가구,...,70.0,200,250,잘 되어 있지 않다,NaN,NaN,NaN,0.000000,0.020568,62.056767
4,5,2020,10000192,1098.806050,수도권,여자,1,그 외 가구,그 외 가구,그 외 가구,...,65.0,250,300,보통이다,NaN,NaN,NaN,0.000000,0.000000,60.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18059,18060,2020,993800291,601.643255,비수도권,남자,3,그 외 가구,그 외 가구,그 외 가구,...,55.0,400,500,보통이다,NaN,NaN,NaN,0.328113,-7.743590,-681.547640
18060,18061,2020,994800251,384.069810,비수도권,남자,5,그 외 가구,그 외 가구,그 외 가구,...,60.0,300,600,잘 되어 있다,NaN,NaN,NaN,1.762821,0.466735,282.955507
18061,18062,2020,994800261,359.114694,비수도권,남자,5,그 외 가구,그 외 가구,그 외 가구,...,NaN,0,0,NaN,56.0,보통이다,"국민연금, 공무원연금 등 공적 연금",1.012658,1.176471,278.912882
18062,18063,2020,994800291,416.635211,비수도권,여자,2,그 외 가구,그 외 가구,그 외 가구,...,60.0,200,300,보통이다,NaN,NaN,NaN,0.000000,0.000000,60.000000
18063,18064,2020,995800261,769.826228,비수도권,남자,5,그 외 가구,그 외 가구,그 외 가구,...,60.0,150,300,아주 잘 되어 있다,NaN,NaN,NaN,0.865340,0.111029,157.636868

In [252]:
data.isnull().sum()

Unnamed: 0                      0
조사연도                            0
가구고유번호(MD제공용)                   0
가중치                             0
수도권여부                           0
                            ...
가구주 은퇴시_적정생활비 충당여부          14274
가구주 은퇴시_생활비 재원마련(2014년~)    14274
DTA                             3
DSR                             1
HDRI                            4
Length: 157, dtype: int64

In [124]:
columns=['DSR','DTA','HDRI','30일 이상 원리금 연체 여부','원리금 연체 여부','부채 증가 원인']
data1 = data[columns]
data1

            DSR       DTA        HDRI 30일 이상 원리금 연체 여부 원리금 연체 여부 부채 증가 원인
0      0.121766  0.326531  104.829621              NaN        없음      NaN
1      0.347382  0.450980  139.836192               없음        있음      NaN
2      0.000000  0.000000   60.000000              NaN       NaN      NaN
3      0.020568  0.000000   62.056767              NaN       NaN      NaN
4      0.000000  0.000000   60.000000              NaN       NaN      NaN
...         ...       ...         ...              ...       ...      ...
18059 -7.743590  0.328113 -681.547640              NaN        없음      NaN
18060  0.466735  1.762821  282.955507              NaN        없음      NaN
18061  1.176471  1.012658  278.912882              NaN        없음      NaN
18062  0.000000  0.000000   60.000000              NaN       NaN      NaN
18063  0.111029  0.865340  157.636868              NaN        없음      NaN

[18064 rows x 6 columns]

In [125]:
data2 =data1[(data1['원리금 연체 여부']=='있음') & (data1['HDRI']>100) & (data1['30일 이상 원리금 연체 여부']=='있음')]
data2

,DSR,DTA,HDRI,30일 이상 원리금 연체 여부,원리금 연체 여부,부채 증가 원인
32,0.000000,67.500000,6810.000000,있음,있음,NaN
78,0.074906,6.044321,671.922770,있음,있음,NaN
111,0.388119,0.423283,141.140181,있음,있음,사업자금(사업용 자산구입 및 운용자금 포함)마련
148,0.000000,11.344538,1194.453782,있음,있음,생활비
162,0.000000,5.240642,584.064171,있음,있음,NaN
...,...,...,...,...,...,...
17903,1.556401,10.079933,1223.633390,있음,있음,사업자금(사업용 자산구입 및 운용자금 포함)마련
17931,0.407806,1.059190,206.699622,있음,있음,NaN
17934,0.000000,15.555556,1615.555556,있음,있음,NaN
18006,0.028311,4.048857,467.716705,있음,있음,NaN
18015,0.288926,1.228534,211.746005,있음,있음,NaN

In [133]:
x=data1[(data1['HDRI']>100) & (data1['원리금 연체 여부']=='있음')]
x['부실가구']='1'
x
# HDRI 100 이상이면서 원리금 연체 된 가구를 부실가구로 정의

<ipython-input-133-4813398c0f4f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['부실가구']='1'

,DSR,DTA,HDRI,30일 이상 원리금 연체 여부,원리금 연체 여부,부채 증가 원인,부실가구
1,0.347382,0.450980,139.836192,없음,있음,NaN,1
32,0.000000,67.500000,6810.000000,있음,있음,NaN,1
58,0.159744,0.397321,115.706584,없음,있음,NaN,1
78,0.074906,6.044321,671.922770,있음,있음,NaN,1
90,0.136038,0.506988,124.302605,없음,있음,생활비,1
...,...,...,...,...,...,...,...
17969,0.335430,27.137767,2807.319759,없음,있음,사업자금(사업용 자산구입 및 운용자금 포함)마련,1
18006,0.028311,4.048857,467.716705,있음,있음,NaN,1
18015,0.288926,1.228534,211.746005,있음,있음,NaN,1
18022,0.607001,0.599577,180.657750,없음,있음,NaN,1
18028,0.270351,0.224764,109.511553,없음,있음,NaN,1

In [145]:
data3 = pd.merge(data1, x, how='outer')
data3

            DSR       DTA        HDRI 30일 이상 원리금 연체 여부 원리금 연체 여부 부채 증가 원인 부실가구
0      0.121766  0.326531  104.829621              NaN        없음      NaN  NaN
1      0.347382  0.450980  139.836192               없음        있음      NaN    1
2      0.000000  0.000000   60.000000              NaN       NaN      NaN  NaN
3      0.000000  0.000000   60.000000              NaN       NaN      NaN  NaN
4      0.000000  0.000000   60.000000              NaN       NaN      NaN  NaN
...         ...       ...         ...              ...       ...      ...  ...
18059  0.197271  0.341098  113.836925              NaN        없음  거주주택 마련  NaN
18060 -7.743590  0.328113 -681.547640              NaN        없음      NaN  NaN
18061  0.466735  1.762821  282.955507              NaN        없음      NaN  NaN
18062  1.176471  1.012658  278.912882              NaN        없음      NaN  NaN
18063  0.111029  0.865340  157.636868              NaN        없음      NaN  NaN

[18064 rows x 7 columns]

In [148]:
data3 = data3.fillna({'부실가구':0})
data3

            DSR       DTA        HDRI 30일 이상 원리금 연체 여부 원리금 연체 여부 부채 증가 원인 부실가구
0      0.121766  0.326531  104.829621              NaN        없음      NaN    0
1      0.347382  0.450980  139.836192               없음        있음      NaN    1
2      0.000000  0.000000   60.000000              NaN       NaN      NaN    0
3      0.000000  0.000000   60.000000              NaN       NaN      NaN    0
4      0.000000  0.000000   60.000000              NaN       NaN      NaN    0
...         ...       ...         ...              ...       ...      ...  ...
18059  0.197271  0.341098  113.836925              NaN        없음  거주주택 마련    0
18060 -7.743590  0.328113 -681.547640              NaN        없음      NaN    0
18061  0.466735  1.762821  282.955507              NaN        없음      NaN    0
18062  1.176471  1.012658  278.912882              NaN        없음      NaN    0
18063  0.111029  0.865340  157.636868              NaN        없음      NaN    0

[18064 rows x 7 columns]

In [56]:
data1.to_csv("HDRI1_2020.csv", mode="w",encoding='euc-kr')

In [ ]:
data4 = pd.merge(data,data3,how='outer')
data4

In [ ]:
data4.to_csv("label_2020.csv", mode="w",encoding='euc-kr')

In [154]:
data['부실가구']=data3['부실가구']
data

,Unnamed: 0,조사연도,가구고유번호(MD제공용),가중치,수도권여부,가구주 성별,가구원수,노인가구,조손가구,한부모가구,...,가구주 미은퇴시_최소생활비,가구주 미은퇴시_적정생활비,가구주 미은퇴시_노후준비상황,가구주 은퇴시_가구주 은퇴실제 연령,가구주 은퇴시_적정생활비 충당여부,가구주 은퇴시_생활비 재원마련(2014년~),DSR,DTA,HDRI,부실가구
0,1,2020,10000112,1531.602344,수도권,남자,3,그 외 가구,그 외 가구,그 외 가구,...,400,500,보통이다,NaN,NaN,NaN,0.121766,0.326531,104.829621,0
1,2,2020,10000132,1314.119926,수도권,여자,2,그 외 가구,그 외 가구,그 외 가구,...,500,700,보통이다,NaN,NaN,NaN,0.347382,0.450980,139.836192,1
2,3,2020,10000162,1098.806050,수도권,여자,1,노인가구,그 외 가구,그 외 가구,...,100,150,보통이다,NaN,NaN,NaN,0.000000,0.000000,60.000000,0
3,4,2020,10000182,1124.027871,수도권,남자,2,그 외 가구,그 외 가구,그 외 가구,...,200,250,잘 되어 있지 않다,NaN,NaN,NaN,0.020568,0.000000,62.056767,0
4,5,2020,10000192,1098.806050,수도권,여자,1,그 외 가구,그 외 가구,그 외 가구,...,250,300,보통이다,NaN,NaN,NaN,0.000000,0.000000,60.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18059,18060,2020,993800291,601.643255,비수도권,남자,3,그 외 가구,그 외 가구,그 외 가구,...,400,500,보통이다,NaN,NaN,NaN,-7.743590,0.328113,-681.547640,0
18060,18061,2020,994800251,384.069810,비수도권,남자,5,그 외 가구,그 외 가구,그 외 가구,...,300,600,잘 되어 있다,NaN,NaN,NaN,0.466735,1.762821,282.955507,0
18061,18062,2020,994800261,359.114694,비수도권,남자,5,그 외 가구,그 외 가구,그 외 가구,...,0,0,NaN,56.0,보통이다,"국민연금, 공무원연금 등 공적 연금",1.176471,1.012658,278.912882,0
18062,18063,2020,994800291,416.635211,비수도권,여자,2,그 외 가구,그 외 가구,그 외 가구,...,200,300,보통이다,NaN,NaN,NaN,0.000000,0.000000,60.000000,0
18063,18064,2020,995800261,769.826228,비수도권,남자,5,그 외 가구,그 외 가구,그 외 가구,...,150,300,아주 잘 되어 있다,NaN,NaN,NaN,0.111029,0.865340,157.636868,0

In [155]:
data.to_csv("label_2020.csv", mode="w",encoding='euc-kr')

# 결정나무모형 돌리기

In [253]:
data = pd.read_csv('./label_2020.csv', engine='python', encoding='cp949')
data = data.iloc[:,5:]
data.isnull().sum()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18064 entries, 0 to 18063
Columns: 154 entries, 수도권여부 to 부실가구
dtypes: float64(38), int64(67), object(49)
memory usage: 21.2+ MB

In [254]:
data['부실가구'].value_counts()

0    17120
1      944
Name: 부실가구, dtype: int64

In [255]:
X.columns

Index(['수도권여부', '가구주 성별', '가구원수', '노인가구', '조손가구', '한부모가구', '다문화가구(2012년~)',
       '장애인가구(2012년~)', '가구주 교육정도_학교', '가구주 교육정도_수료여부',
       ...
       '가구주 미은퇴시_은퇴연령', '가구주 미은퇴시_최소생활비', '가구주 미은퇴시_적정생활비', '가구주 미은퇴시_노후준비상황',
       '가구주 은퇴시_가구주 은퇴실제 연령', '가구주 은퇴시_적정생활비 충당여부', '가구주 은퇴시_생활비 재원마련(2014년~)',
       'DSR', 'DTA', 'HDRI'],
      dtype='object', length=153)

In [256]:
from sklearn.preprocessing import LabelEncoder
items = data['수도권여부'].unique()
encoder = LabelEncoder()
encoder.fit(items)

labels = encoder.transform(items)
print('인코딩 변화값: ', labels)
labels[0]

 encoder.classes_

IndentationError: unexpected indent (<ipython-input-256-f390634474c4>, line 10)

In [257]:
data['수도권여부']= encoder.transform(data['수도권여부'])

ValueError: y contains previously unseen labels: '수도권'

In [258]:
data

,수도권여부,가구주 성별,가구원수,노인가구,조손가구,한부모가구,다문화가구(2012년~),장애인가구(2012년~),가구주 교육정도_학교,가구주 교육정도_수료여부,...,가구주 미은퇴시_최소생활비,가구주 미은퇴시_적정생활비,가구주 미은퇴시_노후준비상황,가구주 은퇴시_가구주 은퇴실제 연령,가구주 은퇴시_적정생활비 충당여부,가구주 은퇴시_생활비 재원마련(2014년~),DSR,DTA,HDRI,부실가구
0,수도권,남자,3,그 외 가구,그 외 가구,그 외 가구,그 외 가구,그 외 가구,대학교(4년제 이상),졸업,...,400,500,보통이다,NaN,NaN,NaN,0.121766,0.326531,104.829621,0
1,수도권,여자,2,그 외 가구,그 외 가구,그 외 가구,그 외 가구,그 외 가구,대학원박사 이상,졸업,...,500,700,보통이다,NaN,NaN,NaN,0.347382,0.450980,139.836192,1
2,수도권,여자,1,노인가구,그 외 가구,그 외 가구,그 외 가구,그 외 가구,초등학교,졸업,...,100,150,보통이다,NaN,NaN,NaN,0.000000,0.000000,60.000000,0
3,수도권,남자,2,그 외 가구,그 외 가구,그 외 가구,그 외 가구,그 외 가구,고등학교,졸업,...,200,250,잘 되어 있지 않다,NaN,NaN,NaN,0.020568,0.000000,62.056767,0
4,수도권,여자,1,그 외 가구,그 외 가구,그 외 가구,그 외 가구,그 외 가구,고등학교,졸업,...,250,300,보통이다,NaN,NaN,NaN,0.000000,0.000000,60.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18059,비수도권,남자,3,그 외 가구,그 외 가구,그 외 가구,그 외 가구,그 외 가구,대학교(4년제 이상),졸업,...,400,500,보통이다,NaN,NaN,NaN,-7.743590,0.328113,-681.547640,0
18060,비수도권,남자,5,그 외 가구,그 외 가구,그 외 가구,그 외 가구,그 외 가구,대학교(4년제 이상),졸업,...,300,600,잘 되어 있다,NaN,NaN,NaN,0.466735,1.762821,282.955507,0
18061,비수도권,남자,5,그 외 가구,그 외 가구,그 외 가구,그 외 가구,장애인가구,대학교(4년제 이상),졸업,...,0,0,NaN,56.0,보통이다,"국민연금, 공무원연금 등 공적 연금",1.176471,1.012658,278.912882,0
18062,비수도권,여자,2,그 외 가구,그 외 가구,그 외 가구,그 외 가구,그 외 가구,대학원석사,졸업,...,200,300,보통이다,NaN,NaN,NaN,0.000000,0.000000,60.000000,0
18063,비수도권,남자,5,그 외 가구,그 외 가구,그 외 가구,그 외 가구,그 외 가구,대학교(4년제 이상),졸업,...,150,300,아주 잘 되어 있다,NaN,NaN,NaN,0.111029,0.865340,157.636868,0

In [259]:
for i in X.columns:
    for j in range(len(data)):
        if type(data[i][j]) == str:
            items = data[i].unique()
            encoder = LabelEncoder()
            encoder.fit(items)
            data[i] = encoder.transform(data[i])

In [260]:
type(data['가구주 은퇴시_생활비 재원마련(2014년~)'][1])

numpy.int32

In [318]:
data2 = data[['수도권여부','가구원수','입주형태','자산'
,'부채'
,'부동산 이외 담보대출'
,'임대보증금'
,'원리금상환액'
,'원금상환액'
,'이자지급액'
,'순자산액'
,'소비지출'
,'여유자금 운용 계획'
,'원리금 연체 여부'
,'30일 이상 원리금 연체 여부'
,'가구주 미은퇴시_최소생활비'
,'부실가구']]

In [313]:
data.fillna(0)

data.isnull().sum()

수도권여부                       0
가구주 성별                      0
가구원수                        0
노인가구                        0
조손가구                        0
                           ..
가구주 은퇴시_생활비 재원마련(2014년~)    0
DSR                         1
DTA                         3
HDRI                        4
부실가구                        0
Length: 154, dtype: int64

In [314]:
data = data.drop(data['DSR'],data['DTA'],data['HDRI'], axis=1)

TypeError: drop() got multiple values for argument 'axis'

In [321]:
X = data2.iloc[:,0:-1]
Y = data2.iloc[:,-1]

In [323]:
Y

0        0
1        1
2        0
3        0
4        0
        ..
18059    0
18060    0
18061    0
18062    0
18063    0
Name: 부실가구, Length: 18064, dtype: int64

In [331]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings('ignore')

# DecisionTree Classifier 생성
dt_clf = DecisionTreeClassifier(random_state=369)

# 학습과 테스트 데이터 셋으로 분리

X_train , X_test , y_train , y_test = train_test_split(X, Y,
                                                       test_size=0.2,  random_state=11)

In [332]:
# DecisionTreeClassifer 학습. 
dt_clf.fit(X_train , y_train)

DecisionTreeClassifier(random_state=369)

In [333]:
pred = dt_clf.predict(X_test)
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [335]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test , pred)
print('결정 트리 예측 정확도: {0:.4f}'.format(accuracy))

# DecisionTreeClassifier의 하이퍼 파라미터 추출
print('DecisionTreeClassifier 기본 하이퍼 파라미터:\n', dt_clf.get_params())

결정 트리 예측 정확도: 0.9015
DecisionTreeClassifier 기본 하이퍼 파라미터:
 {'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': None, 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_impurity_split': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'random_state': 369, 'splitter': 'best'}